name: imagexd19
channels:
  - conda-forge
dependencies:
  - python >= 3.6
  - numpy >= 1.12
  - scipy >= 1.0
  - matplotlib >= 2.1
  - scikit-image >= 0.15
  - notebook >= 4.0
  - itk >= 5.0
  - itkwidgets >= 0.18
  - joblib >= 0.12
  - jupyter_client >= 5.1.0
  - pandas >= 0.20.3
  - scikit-learn >= 0.19.1
  - widgetsnbextension >= 3.5.1
